// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PatientInfo struct {
	ID                string `json:"id"`
	Date              string `json:"date"`
	PcrTotal          int    `json:"pcr_total"`
	PositiveUpTotal   int    `json:"positive_up_total"`
	Positive          int    `json:"positive"`
	PositiveYesterday int    `json:"positive_yesterday"`
	NotSevere         int    `json:"not_severe"`
	Severe            int    `json:"severe"`
	DeathTotal        int    `json:"death_total"`
	DischargeTotal    int    `json:"discharge_total"`
}
